format = 1
name = "Rooted underground province"
seed = 2405

[canvas]
scale = 1
size = [128, 80]
boundary = "world"
background = "forest-day"
horizon = 13

[palette]
D = "dirt"
S = "stone"
G = "grass"
W = "wood"
L = "living-wood"
d = "dirt-wall"
s = "stone-wall"
w = "wood-wall"
l = "living-wood-wall"
"~" = "water"
"=" = "wood-platform"
"|" = "rope"
"*" = "torch"
T = "forest-tree"



[map]
terrain = { file = "terrain.map" }
walls = { file = "walls.map" }
liquids = { file = "liquids.map" }
objects = { file = "objects.map" }
